services:
  db:
    image: postgres:13.16-alpine
    restart: always
    env_file:
      - ./api/.env  # Assuming DB credentials are in this .env file
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - worklog

  api:
    build: ./api
    restart: always
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - worklog

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./frontend/.env
  #   depends_on:
  #     - api
  #   networks:
  #     - worklog

volumes:
  data:

networks:
  worklog:
