services:
  worklog:
    build: ./api
    restart: always
    env_file:
      - ./api/.env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13.16-alpine
    restart: always
    env_file:
      - ./api/.env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
